# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbb0550d57c37a3e7df856514286367072210312804f278436c011deeb5adf0f8c0ffdf6c9218b41bebb512a2d69fca2cc0d8addc9e2282abbf8eaa076a3f28a

test:
  secret_key_base: 4b7e723098df692d4d140591b7caa6c6155dec4d12e98e1a6d62fe0c223647123f33c5e948e60f3dc87f78378a6cf1029fe5b44a3c5a24b821911211f4b29bbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
